env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: alacritty

window:
  padding:
    x: 30
    y: 20

  dynamic_padding: true

  title: Alacritty

  dynamic_title: false

  # Window class (Linux/BSD only):
  # class:
  #   # Application instance name
  #   instance: Alacritty
  #   # General application class
  #   general: Alacritty

  gtk_theme_variant: None

decorations: full

# background_opacity: 0.95
# background_opacity: 1

# Font configuration (changes require restart)
font:
  # The size to use.
  size: 9.2
  # The normal (roman) font face to use.
  normal:
    family: Iosevka Nerd Font
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: Iosevka Nerd Font
    # Style can be specified to pick a specific face.
    style: Regular

  # The italic font face
  italic:
    family: Iosevka Nerd Font
    # Style can be specified to pick a specific face.
    style: Regular

# Colors (Forest night)
schemes:
  forest_night: &forest_night
    primary:
      background: "#323d43"
      foreground: "#d8caac"

    normal:
      black: "#323d43"
      red: "#e68183"
      green: "#a7c080"
      yellow: "#d9bb80"
      blue: "#83b6af"
      magenta: "#d39bb6"
      cyan: "#87c095"
      white: "#d8caac"

    bright:
      black: "#505a60"
      red: "#e68183"
      green: "#a7c080"
      yellow: "#d9bb80"
      blue: "#83b6af"
      magenta: "#d39bb6"
      cyan: "#87c095"
      white: "#d8caac"
    cursor:
      text: "#505a60"
      cursor: "#87c095"
colors: *forest_night

key_bindings:
  # (Windows, Linux, and BSD only)
  # - { key: P,        mods: Control,       action: Paste            }
  # - { key: Insert,   mods: Shift,         action: Paste            }
  # - { key: Slash,    mods: Control,       chars: "gc"              }
  # - { key: Y,        mods: Control,       action: Copy             }
  # - { key: Key0,     mods: Control,       action: ResetFontSize    }
  # - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  # - { key: Minus,    mods: Control,       action: DecreaseFontSize }

  # Vi Mode
  - { key: Space, mods: Shift|Control, mode: Vi, action: ScrollToBottom }
  - { key: Space, mods: Shift|Control, action: ToggleViMode }
  - { key: Escape, mode: Vi, action: ClearSelection }
  - { key: I, mode: Vi, action: ScrollToBottom }
  - { key: I, mode: Vi, action: ToggleViMode }
  - { key: C, mods: Control, mode: Vi, action: ToggleViMode }
  - { key: Y, mods: Control, mode: Vi, action: ScrollLineUp }
  - { key: E, mods: Control, mode: Vi, action: ScrollLineDown }
  - { key: G, mode: Vi, action: ScrollToTop }
  - { key: G, mods: Shift, mode: Vi, action: ScrollToBottom }
  - { key: B, mods: Control, mode: Vi, action: ScrollPageUp }
  - { key: F, mods: Control, mode: Vi, action: ScrollPageDown }
  - { key: U, mods: Control, mode: Vi, action: ScrollHalfPageUp }
  - { key: D, mods: Control, mode: Vi, action: ScrollHalfPageDown }
  - { key: Y, mode: Vi, action: Copy }
  - { key: Y, mode: Vi, action: ClearSelection }
  - { key: Copy, mode: Vi, action: ClearSelection }
  - { key: V, mode: Vi, action: ToggleNormalSelection }
  - { key: V, mods: Shift, mode: Vi, action: ToggleLineSelection }
  - { key: V, mods: Control, mode: Vi, action: ToggleBlockSelection }
  - { key: V, mods: Alt, mode: Vi, action: ToggleSemanticSelection }
  - { key: Return, mode: Vi, action: Open }
  - { key: K, mode: Vi, action: Up }
  - { key: J, mode: Vi, action: Down }
  - { key: H, mode: Vi, action: Left }
  - { key: L, mode: Vi, action: Right }
  - { key: Up, mode: Vi, action: Up }
  - { key: Down, mode: Vi, action: Down }
  - { key: Left, mode: Vi, action: Left }
  - { key: Right, mode: Vi, action: Right }
  - { key: Key0, mode: Vi, action: First }
  - { key: Key4, mods: Shift, mode: Vi, action: Last }
  - { key: Key6, mods: Shift, mode: Vi, action: FirstOccupied }
  - { key: H, mods: Shift, mode: Vi, action: High }
  - { key: M, mods: Shift, mode: Vi, action: Middle }
  - { key: L, mods: Shift, mode: Vi, action: Low }
  - { key: B, mode: Vi, action: SemanticLeft }
  - { key: W, mode: Vi, action: SemanticRight }
  - { key: E, mode: Vi, action: SemanticRightEnd }
  - { key: B, mods: Shift, mode: Vi, action: WordLeft }
  - { key: W, mods: Shift, mode: Vi, action: WordRight }
  - { key: E, mods: Shift, mode: Vi, action: WordRightEnd }
  - { key: Key5, mods: Shift, mode: Vi, action: Bracket }
  - { key: Slash, mode: Vi, action: SearchForward }
  - { key: Slash, mods: Shift, mode: Vi, action: SearchBackward }
  - { key: N, mode: Vi, action: SearchNext }
  - { key: N, mods: Shift, mode: Vi, action: SearchPrevious }

  # (Windows, Linux, and BSD only)
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: F, mods: Control|Shift, action: SearchForward }
  - { key: B, mods: Control|Shift, action: SearchBackward }
  - { key: C, mods: Control|Shift, mode: Vi, action: ClearSelection }
  - { key: Insert, mods: Shift, action: PasteSelection }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: NumpadAdd, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Control, action: DecreaseFontSize }
# bg0:        '#323d43'
# bg1:        '#3c474d'
# bg2:        '#465258'
# bg3:        '#505a60'
# bg4:        '#576268'
# bg_visual:  '#5d4251'
# bg_red:     '#614b51'
# bg_green:   '#4e6053'
# bg_blue:    '#415c6d'
# bg_yellow:  '#5d5c50'
# grey0:      '#7c8377'
# grey1:      '#868d80'
# grey2:      '#999f93'
# fg:         '#d8caac'
# red:        '#e68183'
# orange:     '#e39b7b'
# yellow:     '#d9bb80'
# green:      '#a7c080'
# cyan:       '#87c095'
# blue:       '#83b6af'
# purple:     '#d39bb6'
