env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: alacritty

window:
  padding:
    x: 30
    y: 20

  dynamic_padding: true

  title: Alacritty

  dynamic_title: false

  # Window class (Linux/BSD only):
  # class:
  #   # Application instance name
  #   instance: Alacritty
  #   # General application class
  #   general: Alacritty

  gtk_theme_variant: None

decorations: full

background_opacity: 0.85
# background_opacity: 1

# Font configuration (changes require restart)
font:
  # The size to use.
  size: 9
  # The normal (roman) font face to use.
  normal:
    family: Iosevka Nerd Font
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: Iosevka Nerd Font
    # Style can be specified to pick a specific face.
    style: Medium

  # The italic font face
  italic:
    family: Iosevka Nerd Font
    # Style can be specified to pick a specific face.
    style: Regular
schemes:
  dracular: &dracular
    primary:
      background: "#282a36"
      foreground: "#f8f8f2"
    cursor:
      text: CellBackground
      cursor: CellForeground
    vi_mode_cursor:
      text: CellBackground
      cursor: CellForeground
    search:
      matches:
        foreground: "#44475a"
        background: "#50fa7b"
      focused_match:
        foreground: "#44475a"
        background: "#ffb86c"
      bar:
        background: "#282a36"
        foreground: "#f8f8f2"
    line_indicator:
      foreground: None
      background: None
    selection:
      text: CellForeground
      background: "#44475a"
    normal:
      black: "#000000"
      red: "#ff5555"
      green: "#50fa7b"
      yellow: "#f1fa8c"
      blue: "#bd93f9"
      magenta: "#ff79c6"
      cyan: "#8be9fd"
      white: "#bfbfbf"
    bright:
      black: "#4d4d4d"
      red: "#ff6e67"
      green: "#5af78e"
      yellow: "#f4f99d"
      blue: "#caa9fa"
      magenta: "#ff92d0"
      cyan: "#9aedfe"
      white: "#e6e6e6"
    dim:
      black: "#14151b"
      red: "#ff2222"
      green: "#1ef956"
      yellow: "#ebf85b"
      blue: "#4d5b86"
      magenta: "#ff46b0"
      cyan: "#59dffc"
      white: "#e6e6d1"


# Apply the color scheme.
colors: *dracular
